language: go

go:
  - 1.8

env:
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64

before_install:
  - go get -t ./...
  - go get github.com/GeertJohan/go.rice/rice

install: true

script:
  - rice embed-go
