language: go

go:
  - 1.8

before_install:
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
  - go get -t ./...
  - go get github.com/GeertJohan/go.rice/rice
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable

install:
  - npm install

script:
  - npm run build
  - rice embed-go
